### ISSUE TITLE
Build failing on readthedocs.org

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-docs#93]
Seems that the builds have been failing for the last 4 months when generating epub versions of the docs. https://readthedocs.org/projects/refinebio-docs/builds/

```
Running Sphinx v1.7.6
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33%] faq
reading sources... [ 66%] index
reading sources... [100%] main_text

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] faq

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 403, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 449, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/_epub_base.py", line 373, in write_doc
    StandaloneHTMLBuilder.write_doc(self, docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 608, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/_epub_base.py", line 472, in handle_page
    outfilename, event_arg)
  File "/home/docs/checkouts/readthedocs.org/user_builds/refinebio-docs/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 1038, in handle_page
    (pagename, exc))
ThemeError: An error happened in rendering the page faq.
Reason: TemplateNotFound()

Theme error:
An error happened in rendering the page faq.
Reason: TemplateNotFound()
```

**Comment by arielsvn** [comment]
The error can be reproduced locally by running:

```sh
virtualenv env
source env/bin/activate
pip install -r requirements.txt
cd docs/

../env/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub
```

**Comment by cgreene** [comment]
I disabled the epub output so our build badge is passing. I don't think our docs are likely to be popular e-reader material, so I'm not sure that we need to focus on builds for them.
